apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
nameSuffix: -local
commonLabels:
  env: local
images:
- name: nginx
  newName: registry-jpe2.r-local.net/caas-trial/nginxinc/nginx-unprivileged
  newTag: "1.18"
patches:
- path: sa.yaml
